### ISSUE TITLE
Jsonformat some field is not jsonable

### ISSUE THREAD

**Issue by lxd235** [bersler/OpenLogReplicator#22] opened 2021-03-10 02:49 UTC
#### error desc
1. when i load output file, some field is not jsonable, here is my output file.
![image](https://user-images.githubusercontent.com/18268375/110567552-ae9f1d80-818c-11eb-9da5-45eb7e58fff1.png)
2. i open it with Winhex, content is :
![image](https://user-images.githubusercontent.com/18268375/110567749-f756d680-818c-11eb-8614-7e3bf65b330d.png)
3. i found that only SYS.EXP_HEAD$ is wrong, other is always right

#### env:
1. database **12.2.0.1.0**
2. running platform **Linux localhost.localdomain 3.10.0-862.el7.x86_64 #1 SMP Fri Apr 20 16:44:24 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux**

#### repeat method:
1. new cfg with:
![image](https://user-images.githubusercontent.com/18268375/110568261-af847f00-818d-11eb-9f80-0695a5902345.png)

1. ./src/OpenLogReplicator
2. exe sql
3. `
DROP TABLE "TEST"."EMP1";

CREATE TABLE "TEST"."EMP1" ( "id" NUMBER, "name" VARCHAR2 ( 255 ), "salary" NUMBER, "will_renamed" NUMBER, "will_droped" NUMBER, "will_unused" NUMBER, PRIMARY KEY ( "id" ) );

ALTER TABLE "TEST"."EMP1" ADD ( "added_col" NUMBER ( 7, 2 ) );

ALTER TABLE "TEST"."EMP1" RENAME COLUMN "will_renamed" TO "renamed";

ALTER TABLE "TEST"."EMP1" DROP ( "will_droped" );

ALTER TABLE "TEST"."EMP1" 
SET UNUSED ( "will_unused" );

INSERT INTO "TEST"."EMP1" ( "id", "name", "salary", "added_col", "renamed" ) SELECT ROWNUM
,
'Employee ' || to_char( ROWNUM ),
dbms_random.value ( 2, 9 ) * 1000,
147,
258 
FROM
	dual CONNECT BY LEVEL <= 100;

DELETE 
FROM
	"TEST"."EMP1" 
WHERE
	50 <= "id" 
	AND "id" <= 100;

UPDATE "TEST"."EMP1" 
SET "salary" = 1234;`

**Comment by bersler** [comment] 2021-03-10 23:30
You are right, the reproduction code actually shows situation where JSON output is invalid.
This is because in this case actually the varchar column contains a null (0x0) character. For this case I have updated the code to insert in JSON message unicode character 0 - that is  \\u0000. Fixed committed to master branch.

**Closed by bersler** 2021-03-10 23:30 UTC
