### ISSUE TITLE
Bug: In online mode, the archived logs cannot be queried, causing the program to endlessly search for the archived log path

### ISSUE THREAD

**Issue by hj2016** [bersler/OpenLogReplicator#89] opened 2024-01-10 10:02 UTC
I start the task in online mode to recover from a checkpoint, and there are many archived log files missing in between. After starting, it keeps querying the database for archived log files, but since it can't find them, it gets stuck in an infinite loop without progressing forward.
I have identified some issues with the archived log query statement because the condition IS_RECOVERY_DEST_FILE = 'NO' is being filtered out.
![image](https://github.com/bersler/OpenLogReplicator/assets/18521084/57d3aaa2-fad1-4615-9142-2751ad0ba5ed)
"After modifying IS_RECOVERY_DEST_FILE = 'YES', it can be queried successfully." But information from the DG database is also being queried, which is another issue I've identified here.
![image](https://github.com/bersler/OpenLogReplicator/assets/18521084/4f0e6e75-a191-4c61-ba59-2e50bb6010c6)
After making this modification, there are no issues, and the missing data in between has been captured.
![image](https://github.com/bersler/OpenLogReplicator/assets/18521084/ee0eee2c-9553-4f1c-b731-a733d0acd7e8)

![image](https://github.com/bersler/OpenLogReplicator/assets/18521084/7e4d361f-71ca-4a92-b803-0bfa9ed3c571)

**Comment by hj2016** [comment] 2024-01-10 10:04
Perhaps I can submit a pull request for you?

**Comment by bersler** [comment] 2024-01-10 22:37
Hi @hj2016 , thank you for submitting this issue. I am currently on vacation. I will take a look next week when I am back.

**Comment by bersler** [comment] 2024-03-03 23:32
Hi @hj2016 , the problem is not the fix. The problem is to create a reproduction of the issue to actually verify it. 
Please provide a reproduction of the fault:
1. take docker image for OLR + Oracle (preferred: https://github.com/bersler/OpenLogReplicator-tutorials so that the fault can be reproduced on Oracle XE)
2. set configuration of OLR to ... (preferred: json file)
3. run some SQL commands, restart, whatever else
4. achieve fault

or alternatively for other errors:
1. OLR configuration file
2. OLR checkpoint file set
3. set of redo log files which contain error 
4. achieve fault

**Comment by bersler** [comment] 2024-05-08 20:20
I still am unable to reproduce the issue, I plan to close this issue if nothing changes till end of may.

**Comment by bersler** [comment] 2024-07-18 22:01
Unable to reproduce the issue, closed.

**Closed by bersler** 2024-07-18 22:01 UTC
Labels: bug, reproduction missing
