### ISSUE TITLE
May I ask a few questions

### ISSUE THREAD

**Issue by damobao** [bersler/OpenLogReplicator#183] opened 2024-10-14 16:47 UTC
Our OpenLogRepligator program logs have been frequently showing log number 50039 recently. After reading the code, there are a few areas that I don't quite understand. Can you help me clarify them?
![微信图片_20241015002623](https://github.com/user-attachments/assets/607bf607-6e89-437e-9a16-e50360786997)

1. What are the meanings of the three parameters old, add, and rollback?
2. Why only use the high 32 bits (XIDUSN, XIDSLOT) as part of the key for xidTransactioMap on line 60? Why was the XIDSQN discarded later?
3. On line 62, what is the role of the xidTransactioMap object in the program?
4. Why is the last judgment condition (transaction ->xid!=xid) written like this on line 65? In theory, the same Xid with 32 higher bits may come from different transactions

**Comment by bersler** [comment] 2024-10-14 17:39
I am closing the case because of lack of reproduction. Please reopen when the reproduction becomes available.

**Closed by bersler** 2024-10-14 17:39 UTC
Labels: bug, reproduction missing
