### ISSUE TITLE
BUG: CLOB contents are translated to different language even though there is an entry made in English

### ISSUE THREAD

**Issue by vnykmr36** [bersler/OpenLogReplicator#114] opened 2024-03-01 09:15 UTC
**Table desc:**
```
SQL> desc abcd
 Name     Null?    Type
 -------- -------- -------------
 ID       NOT NULL NUMBER(38)
 NAME              VARCHAR2(80)
 IMAG              BLOB
 DESCR             CLOB
```

**Insert statement:**

```
SQL> insert into abcd select rownum, dbms_random.string('p',60), UTL_RAW.CAST_TO_RAW('This is a test insert into blob column'), to_clob('This is a test insert into clob column') from xmltable('1 to 10');
```

**Source DB inserted data:**

```
SQL> select * from abcd where id=10;

        ID NAME                 IMAG                           DESCR
---------- -------------------- ------------------------------ ------------------------------
        10 :"(mjs`j""NsacxJ^N W 546869732069732061207465737420 This is a test insert into clo
           B?qvqClLJ>H;+_#2Ka9E 696E7365727420696E746F20626C6F b column
           g9[B%vAiwe%?~&%,Fu:5 6220636F6C756D6E
```

**Payload in the file:**

```
{"c_scn":410072,"c_idx":11,"xid":"0x0009.01c.000001a4","payload":[{"op":"c","schema":{"owner":"TEST","table":"ABCD"},"after":{"ID":10,"NAME":":\"(mjs`j\"\"NsacxJ^N WB?qvqClLJ>H;+_#2Ka9Eg9[B%vAiwe%?~&%,Fu:5","IMAG":"546869732069732061207465737420696e7365727420696e746f20626c6f6220636f6c756d6e","DESCR":"周楳<2069>猠愠瑥獴<2069>湳敲琠楮瑯<2063>汯戠捯汵浮"}}]}
```

The issue is true for all 10 rows inserted.

**Comment by vnykmr36** [comment] 2024-03-01 09:16
I've used to_clob function while inserting.

**Comment by bersler** [comment] 2024-03-03 23:34
Can you please provide reproduction steps:

1. take docker image for OLR + Oracle (preferred: https://github.com/bersler/OpenLogReplicator-tutorials so that the fault can be reproduced on Oracle XE)
2. set configuration of OLR to ... (preferred: json file)
3. run some SQL commands, restart, whatever else
4. achieve fault

or alternatively for other errors:
1. OLR configuration file
2. OLR checkpoint file set
3. set of redo log files which contain error 
4. achieve fault

**Comment by bersler** [comment] 2024-03-28 23:55
Hi @vnykmr36 . Did you have chance to find a way to reproduce the issue?
I have tested CLOB and all works good. To fix it I need either the redo log files or a list of steps to reproduce it.
If the problem is not possible to reproduce, I will close the ticket and we can open it back when the problem appears.

**Comment by bersler** [comment] 2024-05-08 20:21
I still am unable to reproduce the issue, I plan to close this issue if nothing changes till end of may.

**Comment by bersler** [comment] 2024-07-18 22:02
Unable to reproduce the issue, closed. We can reopen when we have a reproduction.

**Closed by bersler** 2024-07-18 22:02 UTC
Labels: bug, reproduction missing

**Comment by dima-bzz** [comment] 2026-04-07 10:19
We encountered a similar issue. CLOB data is processed incorrectly, resulting in hieroglyphs in the output.
The problem likely occurs because single-byte characters are treated as double-byte characters.

**Environment:**

Oracle Database 19.11
OpenLogReplicator 1.9.0


**NLS database parameters:**

```sql
PARAMETER	        VALUE
----------------------- ------------
NLS_NCHAR_CHARACTERSET	AL16UTF16
NLS_CHARACTERSET	CL8MSWIN1251

```

Description of the table:

```sql
 Name                                      Null?    Type
 ----------------------------------------- -------- ----------------------------
 ID                                        NOT NULL NUMBER
 DATA_STR                                           VARCHAR2(16)
 DATA_CLOB                                          CLOB
 DATA_NCLOB                                         NCLOB
```


Checkpoint file:

```json
{"row-id":"AAAAACAABAAAbn0AAu","obj":72016,"col":1,"seg-col":1,"int-col":1,"name":"ID","type":2,"length":22,"precision":-1,"scale":-1,"charset-form":0,"charset-id":0,"null":1,"property":[0,0]},
{"row-id":"AAAAACAABAAAb3KAAt","obj":72016,"col":2,"seg-col":2,"int-col":2,"name":"DATA_STR","type":1,"length":16,"precision":-1,"scale":-1,"charset-form":1,"charset-id":171,"null":0,"property":[0,0]},
{"row-id":"AAAAACAABAAAb3KAAu","obj":72016,"col":3,"seg-col":3,"int-col":3,"name":"DATA_CLOB","type":112,"length":4000,"precision":-1,"scale":-1,"charset-form":1,"charset-id":171,"null":0,"property":[128,0]},
{"row-id":"AAAAACAABAAAb3KAAv","obj":72016,"col":4,"seg-col":4,"int-col":4,"name":"DATA_NCLOB","type":112,"length":4000,"precision":-1,"scale":-1,"charset-form":2,"charset-id":2000,"null":0,"property":[128,0]},
```


Insert statement:

```sql
insert into schema1.test(id, data_str, data_clob, data_nclob) values (1, 'test', 'test', 'test');
```

Result:

```json
{"tm":1775475240000000000,"c_scn":228942309088,"c_idx":2,"xid":"0x0022.01e.01916efe","db":"dbdev","payload":[{"op":"c","schema":{"owner":"SCHEMA1","table":"TEST","obj":72016,"columns":[{"name":"ID","type":"number","precision":-1,"scale":-1,"nullable":false},{"name":"DATA_STR","type":"varchar2","length":16,"nullable":true},{"name":"DATA_CLOB","type":"clob","nullable":true},{"name":"DATA_NCLOB","type":"clob","nullable":true}]},"num":0,"rid":"ACepuuAAoAAA5ptAAC","after":{"ID":2,"DATA_STR":"test","DATA_CLOB":"瑥獴","DATA_NCLOB":"test"}}]}
```
